config/routes.rb
Rails.application.routes.draw do
  resources :time_entries
  resources :visits
  resources :user_visits
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"

  get "/book-now" => "visits#new"
  get "/job-board" => "visits#index"
  get "/account" => "application#account"
  get "/schedule" => "visits#schedule"
end

app/models/visit.rb
class Visit < ApplicationRecord
    has_many :user_visits
    has_many :users, through: :user_visits
    has_many :todos
    has_many :time_entries
    accepts_nested_attributes_for :todos

    # def todos 
    #     [@todo1, @todo2]
    # end
    # def todo_attributes=(todo_attributes)
    #     todo_attributes.values.each do |i, todo_attributes|
    #         self.todos.build(todo_attributes)
    #     end
    # end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  before_action :set_visit, only: %i[ show edit update destroy ]

  # GET /visits or /visits.json
  def index
    @visits = Visit.order(scheduled_dudes: :desc)
    @user = current_user
  end

  def schedule
    @visits = User.find(current_user.id).visits
    # @visits = UserVisit.where(user_id: current_user.id).find_each()
    # @visits = Visit.where(UserVisit.where(user_id: current_user.id)).find_each()
  end

  # GET /visits/1 or /visits/1.json
  def show
  end

  # GET /visits/new
  def new
    @visit = Visit.new
    @todo = @visit.todos.new
    # authorize! :manage, @visit
    # @todo = @visit.todos.build
    # @visit.todos.build
  end

  # GET /visits/1/edit
  def edit
  end

  # POST /visits or /visits.json
  def create
    @visit = Visit.new(visit_params)

    respond_to do |format|
      if @visit.save
        format.html { redirect_to root_path, notice: "Visit was successfully created." }
        format.json { render :show, status: :created, location: @visit }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1 or /visits/1.json
  def update
    respond_to do |format|
      if @visit.update(visit_params)
        format.html { redirect_to visit_url(@visit), notice: "Visit was successfully updated." }
        format.json { render :show, status: :ok, location: @visit }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @visit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1 or /visits/1.json
  def destroy
    @visit.destroy

    respond_to do |format|
      format.html { redirect_to visits_url, notice: "Visit was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visit
      @visit = Visit.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def visit_params
      params.require(:visit).permit(:status, :scheduled_date, :scheduled_start, :scheduled_end, :scheduled_dudes, :customer_id,
      todos_attributes: [:id, :visit_id, :content, :is_complete, :completed_by_id, :completed_time, :created_ad, :updated_at])
    end
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/visits/_boardvisit.html.erb
<div class="card">
  <span id="jobcard"> <%= render "visits/visit", visit: boardvisit %> </span>
  <p>
    <%= link_to "Show this visit", boardvisit %>
    <div>
      <strong>DEVELOPER:</strong>
      <div>
        visit.id: <%= boardvisit.id %>
      </div>
      <div>
        associated users: <span id="assocaited-users"><%= boardvisit.user_visits.count %></span>
      </div>
      <div>
        customer_id: <%= boardvisit.customer_id %>
      </div>
    </div>
  </p>
  <%# job buttons %>
  <% if User.find(current_user.id).visits.include? boardvisit %>
      <%= form_with(model: boardvisit.user_visits.find_by(user_id: current_user.id), local: false, method: :delete) do |f| %>
        <%= f.hidden_field :visit, value: boardvisit %>
        <div>
        </div>
        <%= f.submit "Leave Job", class: "job-button-leave" %>
      <% end %>
    <% elsif boardvisit.user_visits.count < boardvisit.scheduled_dudes %>
        <%= form_with(model: boardvisit.user_visits.build, local: false) do |f| %>
          <%= f.hidden_field :user_id, value: current_user.id %>
          <%= f.hidden_field :visit_id, value: boardvisit.id %>
          <div>
          </div>
          <%= f.submit "Join Job", class: "job-button-join" %>
        <% end %>
    <% else %>
      <div class="job-button-full">
        <p>Job Full</p>
      </div>
    <% end %>
</div>

app/views/visits/_form.html.erb
<%= form_with model: @visit do |form| %>
  <% if @visit.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@visit.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% @visit.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :customer, value: 1 %>
  </div>

  <div>
    <%= form.label :scheduled_date, style: "display: block" %>
    <%= form.date_field :scheduled_date %>
  </div>

  <div>
    <%= form.label :scheduled_start, style: "display: block" %>
    <%= form.time_field :scheduled_start %>
  </div>

  <div>
    <%= form.label :scheduled_end, style: "display: block" %>
    <%= form.time_field :scheduled_end %>
  </div>

  <div>
    <%= form.label :how_Many_Dudes?, style: "display: block" %>
    <%= form.number_field :scheduled_dudes %>
  </div>

  <div class="container">
    <h4>Describe your To-do:</h4>
    <%= form.fields_for :todos do |builder| %>
      <%= builder.text_field :content %>
    <% end %>
  </div>

  <div>
    <%= form.submit "Request Job" %>
  </div>
<% end %>

app/views/visits/_schedulevisit.html.erb
<div class="card">
    <span id="jobcard"> <%= render "visits/visit", visit: schedulevisit %> </span>

    <% time_entry = schedulevisit.time_entries.find_by(user_id: current_user.id) %>
    
    <% if time_entry %>
        <% if time_entry.end_time.nil? %>
            <p>Timer started but not ended!</p>
            
            <%# Stop timer %>
            <%= form_with(model: schedulevisit.time_entries.find_by(user_id: current_user.id), local: false, method: :patch) do |f| %>
                <%= f.hidden_field :user_id, value: current_user.id %>
                <%= f.hidden_field :visit_id, value: schedulevisit.id %>
                <%= f.hidden_field :end_time, value: Time.new %>
                <div>
                </div>
                <%= f.submit "Stop Timer", class: "job-button-timer-stop" %>
            <% end %>

            <span id="timer-content">

            </span>

        <% else %>
            <strong><p>Saved time entry:</p></strong>
            <p><%= (time_entry.end_time - time_entry.start_time).round() %> seconds</p>
            <div>
                <%= time_entry.start_time %>
            </div>
            <div>
                <%= time_entry.end_time %>
            </div>
        <% end %>

    <% else %>
        <%# Start timer %>
        <%= form_with(model: schedulevisit.time_entries.build, local: false) do |f| %>
            <%= f.hidden_field :user_id, value: current_user.id %>
            <%= f.hidden_field :visit_id, value: schedulevisit.id %>
            <%= f.hidden_field :start_time, value: Time.new %>
            <div>
            </div>
            <%= f.submit "Start Timer", class: "job-button-timer-start" %>
        <% end %>
    <% end %>

    
    

</div>

app/views/visits/_visit.html.erb
<div id="<%= dom_id visit %>">
  <p>
    <strong>Scheduled date:</strong>
    <%= visit.scheduled_date %>
  </p>

  <p>
    <strong>Scheduled start:</strong>
    <%= visit.scheduled_start %>
  </p>

  <p>
    <strong>Scheduled end:</strong>
    <%= visit.scheduled_end %>
  </p>

  <p>
    <strong>Scheduled dudes:</strong>
    <%= visit.scheduled_dudes %>
  </p>

  <p>
    <strong>Todos:</strong>
    <% visit.todos.each do |todo| %>
      <%= todo.content %>
    <% end %>
  </p>
  
  <p>
    <strong>Team:</strong>
    <% visit.user_visits.each do |team_member| %>
      <%= User.find(team_member.user_id).email %>
    <% end %>
  </p>

</div>

app/views/visits/edit.html.erb
<h1>Editing visit</h1>

<%= render "form", visit: @visit %>

<br>

<div>
  <%= link_to "Show this visit", @visit %> |
  <%= link_to "Back to visits", visits_path %>
</div>

app/views/visits/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Job Board</h1>
  <% if @visits.count == 0 %>
    <h3>There are no jobs available at this time.</h3>
  <% end %>
  <div id="jobboard">
    <%= render partial: "boardvisit", collection: @visits %>
  </div>

  <%= link_to "Home", root_path %>
</div>

app/views/visits/new.html.erb
<div class="container">
  <h1>Book Now!</h1>

  <%= render "form", visit: @visit %>

  <br>

  <div>
    <%= link_to "Back", root_path %>
  </div>
</div>

app/views/visits/schedule.html.erb
<p style="color: green"><%= notice %></p>

<div class="container">
  <h1>Personal Schedule</h1>

  <div id="jobschedule">
    <%= render partial: "schedulevisit", collection: @visits %>
  </div>

  <%= link_to "Home", root_path %>
</div>

app/views/visits/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @visit %>

<div>
  <%= link_to "Edit this visit", edit_visit_path(@visit) %> |
  <%= link_to "Back to visits", visits_path %>

  <%= button_to "Destroy this visit", @visit, method: :delete %>
</div>