config/routes.rb
Rails.application.routes.draw do
  resources :time_entries
  resources :visits
  resources :user_visits
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#home"

  get "/book-now" => "visits#new"
  get "/job-board" => "visits#index"
  get "/account" => "application#account"
  get "/schedule" => "visits#schedule"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def account
        @user = current_user
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/account.html.erb
<div class="container">
    <h1>Account Page</h1>
    <% if current_user %>
        <h3>Email:</h3>
        <h4> <%= current_user.email %></h4>
        <h3>Role:</h3>
        <% current_user.roles.each do |role| %>
            <h4><%= role.name %></h4>
        <% end %>
        <li><%= link_to "Home", root_path %></li>
        <%= button_to "Sign Out", destroy_user_session_path, method: :delete %>
    <% else %>
        <li class="nav-item active">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
        </li>
        <li class="nav-item">
        <%= link_to "Login", new_user_session_path, class:"nav-link" %>
        </li>
    <% end %>

</div>  

app/views/application/home.html.erb
<div class="container">
    <h1>Test page for now</h1>
    <li> <%= link_to "Book Now", "book-now" %></li>
    <li><%= link_to "Job Board", "job-board" %></li>
    <li><%= link_to "Personal Schedule", "schedule" %></li>
    <li><%= link_to "Account", account_path %></li>
</div>

app/views/application/index.html.erb
<div class="container">
    <h1>Test page for now</h1>
    <li> <%= link_to "Book Now", "book-now" %></li>
    <li><%= link_to "Job Board", "job-board" %></li>
</div>